version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          paths:
            - node_modules
          key: $CACHE_VERSION-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:dubnium-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn lint
      - run: yarn format:check

  test1:
    docker:
      - image: circleci/node:dubnium-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn test:ci
   
  e2e-test:
    docker:
      - image: circleci/node:dubnium-browsers
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: tpCi
          POSTGRES_DB: psdb
          POSTGRES_PASSWORD: someNotSecurePassword

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          command: yarn test:e2e
          environment:
             DATABASE_URL: postgres://tpCi:someNotSecurePassword@localhost:5432/psdb
             JWT_SECRET: 'some string yo want'
             API_PORT: '3000'
             API_HOST: localhost
             API_PROTOCOL: http


  build_and_push_docker:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker build --cache-from=app -t app:latest .
            docker tag  app $DOCKER_LOGIN/my-awesome-ci-expr:$CIRCLE_BUILD_NUM
            docker tag  app $DOCKER_LOGIN/my-awesome-ci-expr:latest
            docker push $DOCKER_LOGIN/my-awesome-ci-expr:$CIRCLE_BUILD_NUM
            docker push $DOCKER_LOGIN/my-awesome-ci-expr:latest
            
  
  build_doc:
    docker:
      - image: circleci/node:dubnium

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

            - dependencies-

      - run: yarn doc:build

      - store_artifacts:
          path: doc-server
      



workflow:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - test1:
          requires:
            - build
      - e2e-test:
          requires:
            - test
      - build_and_push_docker:
          requires:
            -build
      - build_doc:
          requires:
            -build
